name: ElmunaEnchants
main: emeraldmc\Main
version: 1.0.0
api: [3.0.0]
author: EmeraldMC

commands:
 enchantmerchant:
  description: "buy enchantments"
  aliases: ["emerchant"]
  usage: /enchantmerchant
